### ISSUE TITLE
How to invoke DCPathButton programmtically?

### ISSUE THREAD

**Issue by hagile** [Tangdixi/DCPathButton#35]
How to invoke DCPathButton programmtically? Is there a way to open menu programmatically.

**Comment by Tangdixi** [comment]
Sorry for the delayed respond.  
For changing the bloom and fold status.  
There are two private method and a instance in __DCPathButton.m__ files  
*  `- (void)pathCenterButtonFold`
*  `- (void)pathCenterButtonBloom`
*  `@property (assign, nonatomic, getter = isBloom) BOOL bloom`  

If U really want to control the button's status by yourself. Move these three to the __DCPathButton.h__.  
It's all yours

**Comment by hagile** [comment]
I think you're not getting my question, however thanks for the reply. My question is to invoke menu without tapping (touching) on DCPathButton. Is it possible? Let me know if you're still not getting me.

**Comment by Tangdixi** [comment]
I know what U want and I found another solution.  
U just invoke the method `- (void)centerButtonTapped` in __DCPathButton.m__.  
Because when U tap the button, this method will be invoked.  
So if U want the same effect which just like touch the button. Invoke this method directly.  
And of course U must add this method to **.h** file to make it public.

**Comment by hagile** [comment]
Ok thanks ! :)
