### ISSUE TITLE
DCPathButton breaks on hidesBottomBarWhenPushed=true

### ISSUE THREAD

**Issue by jsnthan** [Tangdixi/DCPathButton#38]
Hi Tangdixi,

I really love your work on DCPathButton! However, there is a small issue: when I set hidesBottomBarWhenPushed=true before push a UIViewController to a UINavigationController, the tabBar is hidden, but DCPathButton still shows up there. Is there anyway to hide DCPathButton when hidesBottomBarWhenPushed=true?

I have set up a sample project in https://www.dropbox.com/sh/9kfbh3i0pxm3yoz/AABb-2arK7WeChkm9e8SJtY7a?dl=0. In the controller, if you click the "click me" button, the tabBar will be hide except the DCPathButton. If we pop the view, then DCPathButton disappear in the tabBar.

Thanks!

**Comment by Tangdixi** [comment]
This is a view z-axis level issue.  
Because you add the **DCPathButton** in the _TabBarController_'s view, when you set ` hidesBottomBarWhenPushed=true `, the _TabBarController_ actually hide the tabBar but not contain the **DCPathButton**.  
So here is the solution, follow these steps:  
*  change the ** DCPathButton** as a global instance in your _TabBarViewController.swift_
*  Add these code  in your _TabBarViewController.swift_:
```objc
    override func viewDidLayoutSubviews() {
        
        super.viewDidLayoutSubviews()
        
        self.view .bringSubviewToFront(self.centerButton)
        
    }
```
*  Control the **DCPathButton** on your target controller. In your project is the _ViewController.swift_, add thesis two functions:
```objc
    override func viewWillDisappear(animated: Bool) {
        
        super.viewWillDisappear(animated)
        
        let tabBarController = self.tabBarController as! TabBarViewController
        tabBarController.centerButton.hidden = true
        
    }
    
    override func viewWillAppear(animated: Bool) {
        
        super.viewWillAppear(animated)

        let tabBarController = self.tabBarController as! TabBarViewController
        tabBarController.centerButton.hidden = false
        
    }
```   
*  Because the system will auto bring the _TabBar_ to top in z-axis, then it will hide the **DCPathButton**. So we need a final shoot in your _TabBarViewController.swift_
```objc

    override func viewDidLayoutSubviews() {
        
        super.viewDidLayoutSubviews()
        
        self.view .bringSubviewToFront(self.centerButton)
        
    }

```

This will solve your problems, although they are not elegance  
:)

**Comment by Tangdixi** [comment]
Temporary close issue.

**Comment by jsnthan** [comment]
Thanks Tangdixi!
