### ISSUE TITLE
Is there a way to use as UIBarButtonItem

### ISSUE THREAD

**Issue by vikmeup** [Tangdixi/DCPathButton#44]
I have something like this
```
self.navigationItem.rightBarButtonItem = dcPathButton
```

When I press a button, navigation tittle and dcPathButton disappear.

**Comment by Tangdixi** [comment]
Nope ...  
`UIBarButtonItem`'s height is unchangeable.  
Once you click the **DCPathButton**, something weird happen because the limited frame of its super view, the `UIBarButtonItem` it is.  
This is also why I can't put it into a UITabBar. In the Demo, I make the **DCPathButton** as a subview in `UITabBarViewController` and it just like a fake `UITabBarItem`.  
In the same way, you can make a fake one.  Put a fake `UINavigationBar` which is a `UIView` that has a _(screenWidth x 64)_ frame, then put the **DCPathButton** inside.  
And of course, you have to "abandon" the origin UINavigationBar, hide it ....
In my opinion, manipulate a `UIView` is always simple  
:)

**Comment by vikmeup** [comment]
```
if let app = UIApplication.sharedApplication().delegate as? AppDelegate, let window = app.window {
    window.addSubview(dcPathButton)
    window.bringSubviewToFront(dcPathButton)
}
```
I implemented using window, and just hide and show on view will appear and disaster, could not figure it out with Navigation Bar, because it overlays everything else (UINavigationBar as UIView did not work for me)

@Tangdixi Thanks a lot for building this amazing button!
