### ISSUE TITLE
Adding DCPathButton on Tab Bar

### ISSUE THREAD

**Issue by xeravim** [Tangdixi/DCPathButton#58]
Hi,

I really loved this library! But I kinda stuck on this particular issue, I want to add this button on a tab bar instead on view (as in example) but If i had it on the Tab Bar , the DCPathItemButton seems to be unclickable, any solution to these?

    CGFloat heightDifference = buttonImage.size.height - self.tabBar.frame.size.height;
  
    CGPoint center = self.tabBar.center;
    center.y = center.y - self.tabBar.frame.origin.y - heightDifference/2.0 - 8;
    button.dcButtonCenter = center;
  
    // Setting the DCButton appearance
    button.allowSounds = YES;
    button.allowCenterButtonRotation = NO;
  
    button.bottomViewColor = [UIColor grayColor];
    button.bloomDirection = kDCPathButtonBloomDirectionTop;
    [self.tabBar addSubview:button];

**Comment by Tangdixi** [comment]
This is a **Responder Chain** issue.   
According to Apple's [Event Delivery: The Responder Chain](https://developer.apple.com/library/ios/documentation/EventHandling/Conceptual/EventHandlingiPhoneOS/event_delivery_responder_chain/event_delivery_responder_chain.html), it says:  
*If the point passed into `hitTest:withEvent:` is not inside the bounds of the view, the first call to the `pointInside:withEvent:` method returns NO, the point is ignored, and `hitTest:withEvent:` returns nil. If a subview returns NO, that whole branch of the view hierarchy is ignored, because if the touch did not occur in that subview, it also did not occur in any of that subview’s subviews. This means that any point in a subview that is outside of its superview can’t receive touch events because the touch point has to be within the bounds of the superview and the subview. This can occur if the subview’s ` clipsToBounds ` property is set to NO.*  
In your case, because the **TabBar**'s `clipsToBounds` is **NO** in default, so you can see the **DCPathItemButton** appear.   
Set the `clipsToBounds` to **YES** then you'll know why they're unclickable.  
Unfortunately I can't solve your issue now. Because I treat **DCPathButton** as a view, not a UITabBarItem.  
: [

**Comment by xeravim** [comment]
Hi Tangdixi,

thank your for the answer, so what is the best approach to implement this? 
I have seen from the issues here that I should implement hide an unhide to the view, but is it smooth enough?

**Comment by xeravim** [comment]
Nahh.. Nevermind.. Solved. Thanks dude!

**Comment by Tangdixi** [comment]
Congratulations!  
BTW, I copy this button from [Path](www.path.com)
Because it never hide its tabBar, so I chose to implement **DCPathButton** through **UIView**  ~  
But maybe this is not a good idea ...  
So what's your solution ?
